### ISSUE TITLE
Unable to train and generate bins

### ISSUE THREAD

**Issue by sahasrarjn** [atmacvit/bincrowd#2]
Unable to generate bins using the script provided in the binning directory.

Steps to reproduce:
1. `python train.py -d ./dataset_txt/Train_nwpu.txt -f multinomial`
2. `python generate_bins.py  -d ./dataset_txt/Train_nwpu.txt -f multinomial`

Error:
```
Traceback (most recent call last):
  File "generate_bins.py", line 27, in <module>
    best_2(t,fitness_funct=fitness_funct,test_ratio_arr=test_ratio_arr,gammas=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])
  File "/home/suraksha/selcon_sahasra/bincrowd/binning/select_best.py", line 70, in best_2
    testt = json.load(fp)
  File "/home1/anaconda3/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home1/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home1/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home1/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by svshivapuja** [comment]
Hi @sahasrarjn,
This error generally occurs when there is an error in the json generation (i.e. the json is not structured properly).
Could you let me know if there are files generated in the train_jsons or the test_jsons folder?
If yes, please do send those jsons by mail to : svshivapuja@gmail.com.

**Comment by sahasrarjn** [comment]
HI @svshivapuja, yes there are files generated in the train_jsons and test_jsons folder. I have mailed the same to your email address.

**Comment by svshivapuja** [comment]
Hi ! Please do remove the LICENSE file in the select_best, test_jsons and train_jsons  folders and redo the steps. It is resoling the error.
